### ISSUE TITLE
joblib.dump((estimator, y, class_labels), model_save)  fails

### ISSUE THREAD

**Issue by maitlang1** [stevenpawley/r.learn.ml#1]
joblib.dump((estimator, y, class_labels), model_save) 
fails ( variable "class_labels" accessed before initialization) if training data are loaded  from file and not extracted. 

Possible solution that  I found, but there can be better ones:

if load_training != "":
        X, y, cat, group_id = load_training_data(load_training)
        # Initialize variable here or before the "if" block.   
        class_labels = None

**Comment by stevenpawley** [comment]
Thanks for reporting this, the personal repo was a work-in-progress but both of these issues are fixed now.
