### ISSUE TITLE
r.learn.train:  TypeError: bad operand type for unary ~: 'list'

### ISSUE THREAD

**Issue by maitlang1** [stevenpawley/r.learn.ml#2]
Op-system  : OpenSUSE Leap 15.1
GRASS      : 7.9.dev
python        : 3.6.10
scikit-learn  : 0.22.1

Scaling of variables fails. I had one category map (soils) and 9 other feature variables (a selection of Sentinel-2 MSI and Landsat-8 OLI bands). 

 File "/usr/local/grass79/scripts/r.learn.train", line xxx,
in <module>
    main()
  File "/usr/local/grass79/scripts/r.learn.train", line xxx,
in main
    ("scaling", scaler, ~stack.categorical),
TypeError: bad operand type for unary ~: 'list'

**Comment by stevenpawley** [comment]
Thanks for reporting this, the personal repo was a work-in-progress but both of these issues are fixed now.
